### ISSUE TITLE
Numbers not showing on low connectivity devices.

### ISSUE THREAD

**Issue by Narsil** [mathquill/mathquill#110]
On low connectivity devices (3G mainly). Sometimes font loads after the rest and we can type blank characters.

This happens only on numbers, regular ascii characters are fine.

I checked and WOFF support is not yet available for android browser (and I'm pretty sure it never will get it as google is putting all its efforts on chrome it seems).

Possible fixes:
- Desmos way by defaulting to built-in fonts.
- ?

**Comment by EvilOatmeal** [comment]
I have also experienced this when printing in Chrome (on OS X).

The issue is with the Symbola font, and it happens when you have an empty cache and print after you've loaded the page. Even if the font has loaded and is visible in the page it won't show up in the print preview or the print out.

I can reproduce it about 80-90% of the time, but my colleagues can do it less often. When I remove the Symbola font from the MathQuill CSS I can't reproduce it at all. I've been able to reproduce it over multiple Chrome versions (most recently 45) using the "dev" branch of MathQuill.

This is a screenshot of the Chrome print preview:

![math-chrome-print-to-pdf](https://cloud.githubusercontent.com/assets/208614/10016861/3b1f4d22-612a-11e5-8d0e-da6f9eb94867.png)

**Comment by laughinghan** [comment]
I'm not quite sure how you're using MathQuill, but while the default Symbola font file is definitely way bloated, the font file used by MathQuill-basic (as built by `make basic`) is pretty pared-down (thanks Desmos!), so if you don't need any non-ASCII math symbols, it should suffice.

**Comment by EvilOatmeal** [comment]
Thanks for the suggestion, Han. I have seen the basic fonts before but I just assumed that they were too basic, but if Desmos are using them then they might work for us too! I will investigate this further and probably set up some comparison and document my findings.

**Comment by laughinghan** [comment]
That would be wonderful, the docs on MathQuill-basic could be better though I think ASCII is pretty unambiguous, ~ is in basic but &approx; isn't (even though the latter is probably more likely to be encountered by an elementary school math student).

**Comment by kschaefe** [comment]
We have an SVG version of the font.  Why don't we embed each desired character as a data URIs in the CSS?  This would, of course, be a large change to MathQuill because we'd need to use `:before` and ':after` blocks to insert the symbols.  Maybe we could limit that to symbols that are not easily replicated in traditional system fonts or ones that we need to ensure scale well.

**Comment by laughinghan** [comment]
I think it'd be simpler to just embed the font file itself in CSS as a data
URI or similar, which is what Desmos does (with Symbola-basic), unless
there are advantages to your approach I'm not seeing.

Han

**Comment by laughinghan** [comment]
Why not simply embed the font file itself in CSS as a data URI or similar? (It's what Desmos does, with Symbola-basic.)

That's actually why the `Makefile` lets you omit the @font-face declaration by setting the `OMIT_FONT_FACE` env variable (#377), so Desmos can have a custom @font-face declaration with Symbola-basic in a data URI...I guess I should've documented that. The thing is, it's not a great interface right now because it's only relationship to your custom @font-face declaration is via the name "Symbola" in the global namespace of fonts. Which practically is unlikely to cause problems, but isn't very clean; the name doesn't even suggest it has anything to do with MathQuill.

**Comment by EvilOatmeal** [comment]
If you embed the font file it must be very small. A benefit of having an external font file is that it won't be loaded until it's actually used.

And if you need to support multiple font formats all of them will be loaded when embedding, while only the first supported format would be loaded with external fonts.

Depending on how you deliver your CSS and how often it is updated you would also not benefit from the caching that an external font could get.

If you want to preload an external font file you can do so by inserting an element which uses the font.

**Comment by laughinghan** [comment]
To be clear, my suggestion to simply embed the font file was in response to:

> We have an SVG version of the font. Why don't we embed each desired character as a data URIs in the CSS?

Anyway, external font files have many advantages but not showing up on low-connectivity devices is one of their disadvantages, right? Is there any way to address that without embedding the font? Inserting elements that use Symbola is exactly what MathQuill already does and results in this problem, I assume you're suggesting earlier, like, when MathQuill is loaded, `$('<p style="font-family: Symbola; font-size: 16px; position: absolute; top: -20px">Symbola</p>').prependTo('body')` or something?

**Comment by kschaefe** [comment]
Related to the external font files (can make a separate issue if you like):

We have been experiencing a problem with our dialogs that contained MathQuill not being properly positioned.  At the moment we place them, they are properly sized, but by the time they are visible the bottom portion has been clipped.  What I discovered was that the Symbola font "pops in" and causes the MathQuill element to expand because it is larger than Times New Roman.  It seems the browser is using the backup (installed) font to calculate the initial size and at some point later (possibly in the next rendering frame) it places the Symbola characters in, which alters the computed size of the element.

If I use OMIT_FONT_FACE, then the MathQuill is properly sized, since I am eschewing Symbola altogether in that case.

@laughinghan I looked at the Desmos fork and did not see the embedded data-uri version of the font.  Can you give me a pointer?  Is it possible to get that pushed to mathquill/dev as a build option of EMBED_FONT?

@EvilOatmeal There is a 32K limit on data-uris but Symbola-basic is only 7K tff, but there is no basic SVG version.  I would think that SVG would be <32K, but I haven't converted it.

Also, my thought about embedding specific characters' SVG would be to completely eliminate Symbola save for possible images for radicals, etc, by taking advantage of pseudo-element content.  Again this would change the way the project works; probably too drastically at this point.

**Comment by laughinghan** [comment]
> It seems the browser is using the backup (installed) font to calculate the initial size and at some point later (possibly in the next rendering frame) it places the Symbola characters in, which alters the computed size of the element.

Wacky. Browser and OS version?

> I looked at the Desmos fork and did not see the embedded data-uri version of the font. Can you give me a pointer? Is it possible to get that pushed to mathquill/dev as a build option of EMBED_FONT?

Sorry for being confusing, Desmos has a stylesheet to customize MathQuill's appearance by overriding some rules (the gray border, for instance), and in that stylesheet they also embed Symbola-basic as a data URI (and their script to build MathQuill does `OMIT_FONT_FACE=true make`).

> There is a 32K limit on data-uris but Symbola-basic is only 7K tff, but there is no basic SVG version. I would think that SVG would be <32K, but I haven't converted it.

I believe that only IE8 has a 32K limit on data URIs, most browsers are in the megs or gigs (IE9 is [reportedly](http://stackoverflow.com/a/12637435) 4G, Chrome [2M](http://stackoverflow.com/a/6167680)), but SVG isn't for IE at all, it's for Safari on iOS ≤ 4.1, which [doesn't support any other web font format](http://caniuse.com/#search=font-face). (Though, Safari 3.0 on iOS [might be 128K](http://stackoverflow.com/a/6167680).)
