### ISSUE TITLE
why there is a dot and not the symbole x or * when we use multiplication

### ISSUE THREAD

**Issue by kim24** [mathquill/mathquill#369]
is there a way to fix this problem ?
![image](https://cloud.githubusercontent.com/assets/7697100/5730372/75e29998-9b71-11e4-8989-64e6e8d41a73.png)

**Comment by laughinghan** [comment]
You can type \times or \ast or \star for the x or *. \cdot was slightly
arbitrary but I think it's more commonly used than \times after elementary
school, and * is really only used in code rather than in math (it can also
be used in advanced math to mean an arbitrary binary operation, not
necessarily conventional multiplication).

Han
