### ISSUE TITLE
[dev] Mathquill tickles an optimizer bug in Firefox 39 and 40

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#418]
The following code throws `Error: prayer failed: no half-empty fragments`.

```javascript
var elt = document.getElementById("mq");
var mq = MathQuill.MathField(elt);
for (var i = 0; i < 250; i++) {
  mq.latex("a");
}
```

In this case, something is going wrong in the "Fragment" constructor; the first argument passed to it is overwritten with undefined.

It looks like this is a family of bugs, and you can see it crop up in other ways by running the unit tests in the affected versions of Firefox, and noting a group of prayer failures.

This seems like a serious failure in Firefox's optimizer, but I haven't figured out how to slim it down enough to report yet.

**Comment by jwmerrill** [comment]
Note that Firefox 39 is currently in beta, so this bug is scheduled to move to release around June 23.

**Comment by jwmerrill** [comment]
Opened a bugzilla bug for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1171777

Here's a jsbin with a (massively) reduced test case: http://jsbin.com/nohabu/1/edit?js

The problem happens when you use the variable `L = -1` to access properties, i.e. `this.ends[L]`.

We're already seeing this bug show up in bugsnag, so I'm going to fix it by making L and R not be integers. Using integers as object keys is pretty sketchy anyway, since they end up being casted to strings, which can easily lead to subtle bugs even when the js engine is working correctly.

**Comment by laughinghan** [comment]
Wow, you really got it down to the bare minimum! This is really interesting!

It's not going to be trivial to change L and R to not be numbers, lots of code in MathQuill does `-dir`, that was the whole point. Using non-integers like -.5 and .5, or -Infinity and Infinity appears to be an effective workaround for this specific Firefox bug, though.

I'm not sold that number keys are too sketchy to be used in this way, we have no reason to try to extract the key from the object (which would be a string), and MathQuill has never had any known bugs due to this in the years the Desmos version of MathQuill has had L and R.

**Comment by laughinghan** [comment]
> [21:38:49] <sfink>	 thank you for the nice test case, and for tracking it down that far. It seems kinda bad that none of our tests nor our fuzzers caught it.

:smile:

**Comment by jwmerrill** [comment]
This has been fixed in Firefox 40 for a few days, and after updating Firefox 39 (beta) this morning, it's fixed there too.
