### ISSUE TITLE
Superscript rendering off in some cases

### ISSUE THREAD

**Issue by karoltarasiuk** [mathquill/mathquill#424]
When you use this LaTex: `3+\left(\frac{3x\times \frac{7}{8}}{4}\right)^2` you can see that superscript is not in the right position. It should be more to the top. Is this an issue you've noticed before but is a low priority for you guys?

**Comment by jwmerrill** [comment]
This was fixed by https://github.com/mathquill/mathquill/pull/764

Here's the rendering on master:
<img width="116" alt="Screen Shot 2021-11-22 at 2 43 53 PM" src="https://user-images.githubusercontent.com/48409/142924965-3ee66083-cd9d-45fd-91cc-c82efbd635cf.png">

Note that the fix is on master, but you won't see it on mathquill.com yet because the mathquill build on the website hasn't been updated in a while.
