### ISSUE TITLE
[dev] content:'c' in ::after

### ISSUE THREAD

**Issue by edborden** [mathquill/mathquill#426]
What's with the `::after` putting the 'c' in every TextBox? It seems profound, and it's blowing my mind but also adding height.  As I'm sure it has a purpose, and I promise to help document it if someone can explain it to me.

**Comment by laughinghan** [comment]
It was originally so that when there are no contents, the width and height won't collapse to zero. The 'c' should be hidden, and should only be in empty TextBoxes (are those `mathquill-textbox`es?). I have a vague impression this stuff was shuffled around, possibly even refactored to be simpler, on the `dev` branch.

Note that `min-height: 1em` doesn't work because an `em` is the value of the `font-size` property, whereas the actual height of a line box [depends on the font](https://jsbin.com/dahudi/edit?html,output) but is typically larger than the `font-size`, which I wildly conjecture is because of [descenders](https://en.wikipedia.org/wiki/Descender). The upshot is that the only way to know how much vertical space some text will take is to actually render it in the DOM and measure it (unless you either know the  dimensions of the built-in font you're using (like Times New Roman) on all the platforms you care about, or know the dimensions of the custom font and completely trust your `@font-face` declaration on all the platforms you care about).

**Comment by laughinghan** [comment]
Oh, and the reason we want an empty textbox to be the exact height it would be if it had contents, is so that when you start typing, the height doesn't jump around when you type in symbols (like letter variables and numerals and arithmetic operators; as opposed to commands like fractions and square roots, where you expect the height to increase).
