### ISSUE TITLE
[dev] Regression to fix "Keeps blocks from collapsing to zero width/height when empty by inserting invisible text."

### ISSUE THREAD

**Issue by EvilOatmeal** [mathquill/mathquill#470]
Regression introduced in commit ee4c0b3a742a15da270f6cf51a70aa701f774be9.

The code moved into `math.less` will override the fix in `editable.less` because the rules have the same specificity and the rules have now changed order in the compiled code.

![mathquill-height-focus-blur-regression](https://cloud.githubusercontent.com/assets/208614/10048922/836d671c-6215-11e5-8233-4219f1bb9dd0.gif)

@jwmerrill, have you found a fix for Desmos without breaking any other stuff?

**Comment by jwmerrill** [comment]
We don't have a fix for this issue yet—I think you've understood the problem better than we had so far. 

We're actually running a little bit behind master, and this is one of our blockers for getting things up to date.

**Comment by laughinghan** [comment]
Oh, good find! I had been wondering about when this broke and hadn't quite gotten around to looking into it yet...

To confirm, the conflict is between `.mq-math-mode .mq-root-block:after` and `.mq-math-mode .mq-empty:after`, the gray vs black text is just wrong, right? Because the `.mq-root-block` should always be _inside_ the `.mq-editable-field`, so the black selectors can't conflict, right?

I think you could fix this by adding another comma-delimited selector like `.mq-math-mode .mq-root-block.mq-empty:after`.

Also, funny thing, [the TODO on this rule](https://github.com/mathquill/mathquill/blob/ee4c0b3a742a15da270f6cf51a70aa701f774be9/src/css/editable.less#L53) in `editable.less` might've been accomplished already, by e23f3de1a8bd1a6420e498aa9fa7b29397ad338c.

**Comment by EvilOatmeal** [comment]
Yes, the black (matching selector) and gray (non-matching selector) colors are wrong for some reason.

That fix would probably work, but it would add even more to the complexity. I don't understand all the different scenarios as it is. Do you? Could you explain when each selector would match? Then we could possibly simplify the rules or in worst scenario implement the fix you suggested and comment the code.

**Comment by laughinghan** [comment]
On second thought, I guess black and gray are just inverted from what they should be.

You're right, it would need at least a comment saying like, "to override Webkit workaround <link to math.less>" or something.

I think understand both the conflicting selectors, but only because they both have associated comments. I don't understand the other clauses in the comma-delimited list though, I need to go through them. The whole stylesheet...actually the whole codebase needs an audit.

**Comment by EvilOatmeal** [comment]
I changed the test case for the [webkit bug][1] to use "nowrap" instead of "pre" and the bug no longer occurs, so I removed the bug fix which caused this regression.

[1]: https://bugs.webkit.org/show_bug.cgi?id=35443

**Comment by kschaefe** [comment]
Not auto-closed by Github.  Closing because of #472 merge.

**Comment by laughinghan** [comment]
Yeah I'm getting rid of `dev` soon; once we have only a `master` branch, GitHub will start auto-closing issues again.
