### ISSUE TITLE
Emitted command spacing question

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#482]
Currently, when a user types `y~4x`, MathQuill emits `y\sim4x`.

I'm not 100% sure how LaTeX's command lexing works. How does LaTeX know that the 4 should not be part of the `\sim` command? Is it that numerals are not allowed in commands? Or does it use a shortest match rule?

Depending on the answer to that question, maybe it would be better for MathQuill to instead emit

```y\sim 4x```

in this case (note the extra space).

**Comment by laughinghan** [comment]
Right, digits aren't allowed in TeX control words, unlike SGML character entity references. (There's no shortest or longest match rule; `\sinx` is invalid even though `\sin` exists, we have to do `\sin x`.)

> A control sequence in TeX starts with an escape character, which is usually mapped to the backslash character `\`. This is either followed by letters to form a control word, or by a single non-letter to form a control symbol. Control words are terminated by a non-letter, if this happens to be a space character then it is not used to effect the spacing of the document.

https://en.wikibooks.org/wiki/TeX/definition/control_sequence

(More authoritative sources like the TeXbook are even more long-winded.)

Do you nonetheless think it's important for MathQuill to emit an extra space in this case? It's not like we try to emit minimal LaTeX. We include a space in empty groups (`{ }` rather than `{}`) to accommodate a CodeCogs bug, we emit `\frac{1}{2}` and `\sqrt{2}` instead of `\frac12` and `\sqrt2` for readability, and I plan to eventually emit `x^2 y` instead of `x^2y`, also for readability. This doesn't seem as egregious as those cases though.

**Comment by jwmerrill** [comment]
I don't think it's necessary to make a change here. Just wanted to run it by you.
