### ISSUE TITLE
Delayed "click" on touch devices

### ISSUE THREAD

**Issue by DanielKeeble** [mathquill/mathquill#502]
Using the write and cmd functions on a MathQuill input field is incredibly slow on iOS devices, but is not apparent on any other type of device or browser. I have noticed that this issue does not appear on Desmos.

Could someone advise as to how this could be overcome/fixed?

Many thanks.

**Comment by jwmerrill** [comment]
Can you be more specific? What did you do, and how did you determine that
it was slow?

**Comment by DanielKeeble** [comment]
So I have created a "virtual keyboard" which contains a bunch of math symbols. Upon clicking these buttons, they input the appropriate symbol into the MathQuill input (think Desmos).

I have discovered that using the 'substituteTextarea' parameter to use a span on iOS has improved performance significantly, however it still isn't quite there.

Also, by slow I mean there is a significant delay from clicking the button, to it being inputted into MathQuill.

Many thanks.

**Comment by jwmerrill** [comment]
Are you listening for a "click" event on the buttons to input the symbols?

iOS (and other touch systems I know of) wait for ~300ms after you have
tapped the screen before firing a click event. They do this because they
are waiting to see whether you are about to tap again to perform the
double-tap-zoom gesture.

There are several different solutions to this problem with different
tradeoffs. Honestly, none of them are 100% satisfying. Here are a couple
resources:

http://www.sitepoint.com/5-ways-prevent-300ms-click-delay-mobile-devices/

https://github.com/ftlabs/fastclick

FWIW, Desmos uses a custom touch library to address this issue that is not
publicly available.

**Comment by jwmerrill** [comment]
I communicated with Daniel out-of-band, and it sounds like fastclick is looking promising. I'm going to close this because it's more of a mobile-web issue than a mathquill issue.

**Comment by DanielKeeble** [comment]
Thanks again for your help Jason.

**Comment by jwmerrill** [comment]
Sure thing!
