### ISSUE TITLE
Usage in README is very confusing to beginners

### ISSUE THREAD

**Issue by yihui** [mathquill/mathquill#521]
I just discovered this project today, and when I started to try it, I was almost at a total loss, because the usage in README said we could use the `MathQuill` object, but it does not really exist after I followed the download link to download the latest tarball (0.9.4). I spent more than an hour trying to figure out why it didn't work, and it turned out to be a dramatic API change.

So I'd suggest either stay with the old usage to be consistent with the latest tarball, or provide a tarball that actually works with the latest API. It is so confusing that the usage is new, but the software is old. Anyway, thanks a lot for this project. It looks very interesting and useful!

**Comment by laughinghan** [comment]
Oh shit the downloads page

Thanks so much for pointing this out!

Now that I think of it this is kind of a fundamental problem with having the homepage just refer to the README for documentation, since any unreleased changes on `master` should be reflected in the README on `master` but won't yet be in the latest tarball. The right answer to that is a proper docs section of the website, though, and the changes won't usually be this dramatic.

I guess for now I just super need to release v0.10.0

**Comment by yihui** [comment]
Yeah, it will be perfect if you can release v0.10.0 soon. Thanks again!

**Comment by jwmerrill** [comment]
Alternatively, just point the homepage at the README from the latest
release, instead of from master.
