### ISSUE TITLE
Better error message if jQuery isn't loaded

### ISSUE THREAD

**Issue by laughinghan** [mathquill/mathquill#534]
> TypeError: _superclass is undefined

https://mathquill.slack.com/archives/mathquill/p1456625051000204

(In my browser I get `Uncaught TypeError: Cannot read property 'prototype' of undefined`, but it's the same deal)

**Comment by The-Penultimate-Defenestrator** [comment]
I just noticed this too. How easy would it be, though, to remove the dependancy altogether? In other words, how heavily does this project use jQuery? 

I myself am not a huge jQuery fan, since I have a kind of arrogant attitude about not supporting crappy browsers, and since it's not really necessary with the state of the vanilla APIs in 2016 😛

**Comment by laughinghan** [comment]
I think it's pretty tractable to get rid of the jQuery dependency, and I think it wouldn't drastically hurt our support for crappy browsers either.

Vanilla APIs, including the well-supported ones, are just awful though. Like having to use `parentNode.insertBefore(existingChild, newChild)` instead of `.insertBefore()`/`.insertAfter()`/`.appendTo()`/`.prependTo()`/`.before()`/`.after()`/`.append()`/`.prepend()`, what's up with that? It's just a bizarre API design.

**Comment by The-Penultimate-Defenestrator** [comment]
I only see 8 instances of `wt` in `mathquill.min.js`, and no instances of `$(` or `$.`, which indicates that this might be fairly trivial. If there's really only 8 things to change, this will be really easy, but I suspect I'm missing something.

**Comment by laughinghan** [comment]
How many instances of `.jQ`?

**Comment by The-Penultimate-Defenestrator** [comment]
Oops, 144 of those 😛
