### ISSUE TITLE
MathQuill Code of Conduct

### ISSUE THREAD

**Issue by stufflebear** [mathquill/mathquill#564]
MathQuill should have a code of conduct. I adapted this from the code of conduct that @jneen uses for [tulip](https://github.com/tulip-lang/tulip).

https://docs.google.com/document/d/18hrSALV-dSJxagFBXMKUp3u26v5T693qNZ8ZzCUoGZA/edit?usp=sharing

Thoughts and comments appreciated.

**Comment by laughinghan** [comment]
One of things I had wondered about CoCs when I first encountered them was why they have to be so long-winded and specific, rather than being succinct and agreeable like Noisebridge's "be excellent to each other", and today I ran across this really good explanation why, and which cites a concrete failure of "be excellent to each other" that lead to Noisebridge adopting a much more specific Anti-Harassment Policy: https://www.ashedryden.com/blog/codes-of-conduct-101-faq#cocfaqnegative

Also, closing this now that the Code of Conduct in our docs is linked to by the README.
