### ISSUE TITLE
Question / bug ? : symbola is *NOT* used - is this intentional ?

### ISSUE THREAD

**Issue by michel2bec** [mathquill/mathquill#586]
If I go on the mathquill.com page and look at the "b" letter that is autotyped with the dev tools of my browser (so far I have tried Edge and FireFox), I see that it is displayed with the explicit "mq-nonSymbola" option.

as in : 

```
.mq-math-mode var, .mq-math-mode .mq-text-mode, .mq-math-mode .mq-nonSymbola {
  font-family: "Times New Roman",Symbola,serif;
  line-height: 0.9;
}
```

Is this intentional ? It basically mean that all non big symbols are nonSymbola ?

When I do a quick read of the JavaScript code I get the feeling that this was intended to be limited to a handfull of special cases via the NonSymbolaSymbol class.

**Comment by laughinghan** [comment]
This is intentional, but it does not mean big symbols are not Symbola.

Letter variables (both roman and greek) are italicized in math, but Symbola has no italic variant and though modern browsers can apply a slant to custom fonts that don't have italic variants, it looks much worse than italicized Times New Roman.

However, most upright (non-italicized) symbols are in Symbola, including big symbols like capital Sigma for summation, as well as mundane plus + , minus &minus; , infinity &infin; , etc symbols.

Yeah, there are a few limited special cases where upright symbols are overridden to also be in Times New Roman because the Symbola glyph is totally wacky, like percent %.

Hopefully this distinction goes away when we switch to STIX like MathJax and KaTeX use.

Does that answer the question?

**Comment by michel2bec** [comment]
Thanks a lot for your answer, it makes ense and clarifies things.
  I was trying to implement \mathbb{A-Z}, \mathcal{A-Z} (using mathjax font) for my particular use case and I had a feeling the css was activelly fighting the logic of the js code.
  Now I found a way to do it.
