### ISSUE TITLE
Suggestion - Question

### ISSUE THREAD

**Issue by projetmbc** [mathquill/mathquill#593]
Hello.

How hard would be to add other syntax than the LaTeX one ? I think that people who LaTeX do not really need to have an interactive editor but I can be wrong. On the opposite, others would like to use an easier syntax, even if it would be less powerful. I think about [AsciiMath](http://asciimath.org).

**Comment by The-Penultimate-Defenestrator** [comment]
Very hard. The point of this is to have an interactive editor that works in
the web. If you're concerned about usability, I'd try making buttons in
your interface as "shortcuts".

**Comment by laughinghan** [comment]
@projetmbc: to clarify, are you talking about a syntax to use with the API (so, alongside the `.latex()` method, a `.asciimath()` method), or are you talking about instead of typing backslash commands, typing AsciiMath directly in math fields?

Typing AsciiMath directly in math fields seems tricky, seems like there are lots of cases where that model wouldn't fit with MathQuill's. Implementing a `.asciimath()` method would be a significant investment of work but would be straightforward in the sense that the current architecture is reasonably suited for such a task, it really wouldn't be that much different from exporting/importing LaTeX, so it least it wouldn't be requires-refactoring-and-rearchitecting hard.

Thanks for your interest, by the way!

**Comment by projetmbc** [comment]
I was thinking of typing AsciiMath. If it is too hard to do, just not spend time to do it. That was just a suggestion.
