### ISSUE TITLE
If `NODE_ENV=production`, `make` fails

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#597]
Because `npm install` doesn't install the `devDependencies`, which are necessary for running the build.

I think the fix here is probably to explicitly set `NODE_ENV=development` for the `npm install` command, since I can't find any other reliable way to ask for dev dependencies to be installed, independent of the parent environment (you can opt out of installing dev dependencies with `--production`).

It's also possible that these dependencies should not be dev dependencies, since they are necessary for the function of the package.

**Comment by laughinghan** [comment]
Interesting, since MathQuill can't really be installed as a package as-is, I was considering injecting a `package.json` into the `build/` folder and uploading that as an installable package to NPM; in that case, maybe making them `dependencies` rather than `devDependencies` could make sense.

That's not really how NPM is supposed to be used though. If we stick to the notion that `make` is supposed to build the development repo of MathQuill into the usable, installable package, then `make` should probably force `NODE_ENV=development`.

**Comment by laughinghan** [comment]
Was just poking around, apparently `--production=false` will also ask for `devDependencies` to be installed: https://github.com/npm/npm/issues/6803#issuecomment-75621914

Naturally that's not clearly documented, although I guess arguably it's implied by:

> #### production
>
> - Default: false
> - Type: Boolean
>
> Set to true to run in "production" mode.

https://docs.npmjs.com/misc/config#production

**Comment by jwmerrill** [comment]
Oh cool. I bet everyone who uses npm has their own different mental model of how and when `devDependencies` are installed. I know that I had an incorrect one that I was reasonably confident about before today.
