### ISSUE TITLE
Feature Request: Render LaTeX

### ISSUE THREAD

**Issue by laughinghan** [mathquill/mathquill#6]
This functionality was present in the old LatexLive, MathQuill _must_ implement this.

**Comment by ninbit** [comment]
Hi, how can I render Latex directly from MathQuill input? Auto conversion of brackets prevents to enter latex syntax to MathQuill input. For example, `\xleftarrow[a]{b}` _(which is not supported by MathQuill for now)_ is not rendered because first left brackets is automatically converted to text, hence the syntax is broke down.

I know auto conversion is the main thing of MathQuill but wouldn't it be better if there is an option to do this i.e. support for latex syntax?
