### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by benbro** [mathquill/mathquill#670]
Are there plans to remove the jquery dependency?
Modern browsers don't really need it.
A separate polyfill can be used for old browsers.

Making MathQuill self contained without external dependencies will make it smaller and easier to integrate MathQuill with Angular/React project

**Comment by liuhong1happy** [comment]
I also have such a demand。Are there plans to remove the jquery dependency and integrate MathQuill with Angular/React project.

**Comment by bensquire** [comment]
I also would like to see this happen :) +1

**Comment by controversial** [comment]
I'd love to see this happen

**Comment by hermanbergwerf** [comment]
Absolutely! I am currently working on a Dart wrapper for MathQuill and I was horrified when I saw that I have to include jQuery. If I had the balls I would write a Dart port of MathQuill ;-).

**Comment by hermanbergwerf** [comment]
A quick search for `$(` and `jQuery(` through the entire project revealed jQuery is only used in very few places. It is mainly used for tests and I think the tests and the core is/should be independent (e.g. we can remove jQuery from the core while keeping it in the tests for now). Replacing jQuery would also give some cleaner code. I think `$('<span class="mq-cursor">&#8203;</span>');` is a bit dirty, the clean JS solution would be:
```javascript
var span = document.createElement('span');
span.className = 'mq-cursor';
span.innerHTML = '&#8203;'
```
This way no XML has to be parsed.
Some jQuery stuff has been in browsers for quite a while (i.e. the querySelector has been in browsers for years, it is even supported by IE 8!, people who are still using IE 7 should quickly upgrade their system before they are invaded anyway :wink:)

**Comment by laughinghan** [comment]
> A quick search for `$(` and `jQuery(` through the entire project revealed jQuery is only used in very few places.

Unfortunately this is misleading, because even though jQuery objects are _created_ in very few places, they are passed around and jQuery methods are _called_ all over the place, quite possible in literally every source file.

**Comment by laughinghan** [comment]
> querySelector has been in browsers for years

Pretty irrelevant, but fun (to me) side note: MathQuill not only doesn't use querySelector, MathQuill actually overrides `$` internally (to add some custom features) such that `$(selector)` is broken: https://github.com/mathquill/mathquill/blob/560c055dcf3320a3ef3ed879d87408ba8824a58c/src/tree.js#L39

**Comment by laughinghan** [comment]
I just realized I never answered this original question and only mentioned this elsewhere, but yes, the medium-term plan is indeed to remove jQuery, possibly in such a way that jQuery can be provided to add support for older browsers. This isn't considered pressing, however.

**Comment by laughinghan** [comment]
Even further irrelevant side note:

> Replacing jQuery would also give some cleaner code. I think `$('<span class="mq-cursor">&#8203;</span>');` is a bit dirty, the clean JS solution would be:
```javascript
var span = document.createElement('span');
span.className = 'mq-cursor';
span.innerHTML = '&#8203;'
```
This way no XML has to be parsed.

Strictly speaking, `span.innerHTML = '&#8203;'` also hits the parser, but I know what you mean. 😛 

I dunno what "clean" means to you, but I think the HTML string is dramatically more readable because when I think of a DOM element, I think in HTML syntax, and I think that is extremely common, that's why Developer Tools uses HTML syntax to represent DOM elements:

<img width="610" src="https://cloud.githubusercontent.com/assets/225809/19952204/b93f3398-a120-11e6-99b4-2dc16bfb211a.png">

If you're talking about the fact that `createElement()` is faster than the string parsing, this is true (in this case), but it happens once during pageload, it's not like it's an inner loop; I'd say the improved readability far outweighs the negligible performance impact.

Of course, the readability comes nowhere close to the weight of the entire jQuery dependency, much of which MathQuill doesn't even use. Kill it! Kill it with :fire:!

**Comment by hermanbergwerf** [comment]
Yeah, you are right. With clean I mean 'best practice' (especially in the
light of performance). But I agree that the xml string is more readable.
This is done a couple of times so you could make a `span('mq-cursor',
'&#8203;')` function.

It's cool how in the angular2 Dart port/rewrite they now compile component
HTML files to Dart code to improve performance.

**Comment by samgabriel** [comment]
It would be great if jquery is removed. We are looking at this as well for a comprehensive large application that does not use jquery and it would be great if no jquery is involved

**Comment by jagannathTL** [comment]
I love performance of Mathquill then the rest of the LaTex plugins on the market, but due to compatibility issues with Angular2/Ionic2/React so I had to say goodbye to marvelous utility though I would love to see Mathquill without external dependency so we can use in future.

**Comment by ysulyma** [comment]
+1, I've been working hard on getting jQuery out of my app and would hate to have to put it back in.

**Comment by saivan** [comment]
Same here, I think I'm not alone when I say that jquery is just way too big to include in my app - so I just don't use mathquill because of it. I find that sad! :(

**Comment by johanneswilm** [comment]
It looks like MathQuill is no longer maintained (?) so this will likely not ever get resolved. The successor, [Guppy](https://github.com/daniel3735928559/guppy) is [not yet set up for LaTeX import](https://github.com/daniel3735928559/guppy/issues/114). So while we wait for that to happen, I made [this package](https://www.npmjs.com/package/mathquill-jquery) which bundles jQuery and MathQuill together so that one can use MathQuill in ES2015 code without having jQuery available in the window object.

I am more than willing to hand this over to someone else who has more of a stake in MathQuill.

**Comment by johanneswilm** [comment]
Very nice! Maybe it should be added to this list: https://github.com/mathjax/MathJax-docs/wiki/List-of-web-based-math-editors ? (It not being there is likely the main reason I hadn't found it yet - the other reason being that it didn't come up as a search result on Google or npmjs).

**Comment by kschaefe** [comment]
Any more thoughts on this @laughinghan?  I know that I would really prefer to not be in the business of using jQuery.  This library is the only dependency that I have that needs jQuery and I really prefer not to ship it.  Furthermore, I really don't want my devs thinking it's OK to use jQuery because we had to bring it in for MathQuill.

I did a quick pass and to review where jQuery is used and there are so many handles for jQuery bits.  I'd be happy to lend a hand to a `feature/no-jquery` branch, if you could provide some guidance on where and how to tackle this.

**Comment by laughinghan** [comment]
Hey @kschaefe ! I have no love for depending on jQuery either. I'm not sure what specific guidance you're looking for, but I believe we use jQuery solely for DOM manipulation (which, yes, happens everywhere), listening for events, and CSSOM measurements in the stretching of parentheses and square-root characters. It's also used for the same things in tests.

You could also try bundling a subset of Zepto.js, which is supposed to have a mostly jQuery-compatible API?

You already have a commit bit, but I can try to review the PR if you submit one

**Comment by leonfrischauf** [comment]
This would be also especially important for us!
