### ISSUE TITLE
Is it really latex or is it CSS?

### ISSUE THREAD

**Issue by lordadamson** [mathquill/mathquill#682]
Hi guys. I'm a really big fan of mathquill and I think the devs are awesome!
I was wondering how does it work? Is there really a latex engine that renders latex or is it all CSS that looks like latex?
If it's the former then how do you make it editable? If the latter, then where does the latex code come from, do you generate it? and why?
Is it a mix between the two somehow?

So yeah I'm a big fan of the project and would love to understand how it works. I'm developing [LatexCalculator](https://github.com/lordadamson/latexcalculator) using the awesome mathquill.

**Comment by laughinghan** [comment]
Glad to hear it, LatexCalculator looks cool!

By "latex engine" do you mean Knuth's original binaries that most desktop TeX-derived applications (LaTeX, ConTeXt, XeTeX, etc) are based on, or do you just mean software that can render TeX formulas? The code was written from scratch by the contributors, no code from existing latex engines was used, but MathQuill itself could be considered a latex engine, since it can render a subset of LaTeX.

The technique our MathQuill-as-a-latex-engine uses is unique in that it is almost entirely CSS-based, much moreso than even other browser latex engines like MathJax. Knuth's original code actually interprets LaTeX as mutative commands; MathQuill, like MathJax, parses it as a declarative tree syntax (but renders it with very different techniques).

Our internal tree model is used to generate latex code yes, but that's only used for import and export of math, it doesn't even match our internal tree model very well.

Making it editable is magic, in both the good and bad sense. The cursor is a span with a border, and a `setInterval()` toggles its visibility to blink it when a hidden textarea is focused; listeners for keyboard events like typing, arrow keys, backspace etc are attached to the textarea and perform the corresponding action on the spans for the cursor and each character of math, so for example, if the listener on the hidden textarea gets a backspace, the span for character to the left of the cursor span is removed. Does that make sense?

**Comment by lordadamson** [comment]
Yes. Yes it does make sense. And it makes me admire the project even more :D So for example the event listener hears the "/" key pressed and it inserts a `\frac` into the tree and renders again, and the cursor position is adjusted accordingly. Do I understand correctly?

**Comment by laughinghan** [comment]
That's exactly right, except once we modify the DOM tree, the browser automatically re-renders, that's not a specific action.

**Comment by lordadamson** [comment]
Perfect. Thank you :D I'll close the issue now.

**Comment by lordadamson** [comment]
And hey maybe you could add the info you provided me in the Under the hood section in the docs? I guess that would help any other curious folks out there :))
