### ISSUE TITLE
Copying from mq input is broken in Safari 10

### ISSUE THREAD

**Issue by jwmerrill** [mathquill/mathquill#686]
Repro:

1. Go to http://mathquill.com in Safari 10
2. Type an expression into the input box
<img width="689" alt="image" src="https://cloud.githubusercontent.com/assets/48409/19494156/953098c4-9532-11e6-8e2f-91660aad8203.png">
3. Press cmd-c to copy
4. Your paste buffer is empty.

**Comment by jwmerrill** [comment]
This appears to be a regression between the version of mathquill used in Desmos API v0.6 and Desmos API v0.7

https://www.desmos.com/api/v0.6/docs/index.html
https://www.desmos.com/api/v0.7/docs/index.html

**Comment by jwmerrill** [comment]
Bisected this down to 058297a18e17e4aba0.

**Comment by jwmerrill** [comment]
I have verified that removing

```css
* {
  box-sizing: border-box;
}
```

fixes this problem.

WTF...

**Comment by laughinghan** [comment]
So bizarre

**Comment by laughinghan** [comment]
Minimal test case to repro the problem in Safari Version 10.0 (11602.1.50.0.10): http://output.jsbin.com/nonufoxohu

It's been fixed in WebKit Version 10.0 (11602.1.50.0.10, r207537) (tested the minimal test case, and copy-pasting from the MathQuill test page on the commit before the fix, and the Desmos calculator).

(I made a cursory search for a relevant WebKit bug tracker ticket, but couldn't find one.)

**Comment by jwmerrill** [comment]
Nice. I googled around some and didn't find any other references to this issue. Glad to hear it's already fixed in WebKit.
