### ISSUE TITLE
Can we have OnFocus and OnBlur events?

### ISSUE THREAD

**Issue by jbbpatel94** [mathquill/mathquill#905]
This isn't really an issue, but more of a request/suggestion. It would be quite useful to know when the field is focused or not through listeners. Any possibility of this being added?

**Comment by kschaefe** [comment]
You can already do this by attaching listeners to the backing textfield.

**Comment by jbbpatel94** [comment]
@kschaefe can you please share the some sample code here

**Comment by viktorstrate** [comment]
@jbbpatel94 you can do like so :)
First get the root DOM element with `.el()`, then get the `textarea` that is responsible for the events with the `querySelector`.
Next an event listener is added with `addEventListener`, it is important to use the `focusin` and `focusout` events, instead of the regular `focus` and `blur` as they don't [bubble](https://javascript.info/bubbling-and-capturing).

```javascript
// Focus
mathField.el().querySelector('textarea').addEventListener('focusin', () => console.log('FOCUS'))

// Blur
mathField.el().querySelector('textarea').addEventListener('focusout', () => console.log('BLUR'))
```

**Comment by jbbpatel94** [comment]
@viktorstrate thanks
